---
# tasks file for ocp-rhv-gather-info
- name: create silent config file for ovirt gather
  template:
    src: gather-ovirt-info.yml.j2
    dest: /root/gather-ovirt-info.yml
  vars:
    hostname: "{{hostvars[host].name}}"
    cluster_name: "{{cluster_name}}"
    template_name: "rhcos-master"
    result_json_path: "/tmp/{{cluster_name}}"

- name: running playbook on engine
  command: ansible-playbook /root/gather-ovirt-info.yml
  register: ansible_output

- name: collect cluster info json files from  the engine
  fetch:
    src: "/tmp/{{cluster_name}}"
    dest: "res/ovirt.json"
    flat: yes