- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    engine_url: https://localhost/ovirt-engine/api
    engine_user: admin@internal
    engine_password: @@ADD PASSWORD@@
    engine_cafile: /etc/pki/ovirt-engine/ca.pem
    engine_insecure: true

    image_download_timeout: 600
    qcow_path: /tmp/rhcos.qcow2
    qcow_url: file:///tmp/rhcos.qcow2
    template_disk_storage: ibm-nfs
    template_disk_size: 30GiB
    template_seal: false
    template_timeout: 600
    templates:
      - template_name: rhcos-master-ovirt20-8G
        template_cluster: cluster-ovn
        template_memory: 8GiB
        template_cpu: 4
        template_nics:
          - name: nic1
            profile_name: ovn-vmnet-20
      - template_name: rhcos-master-ovirt20
        template_cluster: cluster-ovn
        template_memory: 16GiB
        template_cpu: 8
        template_nics:
          - name: nic1
            profile_name: ovn-vmnet-20
  pre_tasks:
    - name: check if file exists
      stat: path="{{ qcow_path }}"
      register: st
    - name: download rhcos image if missing
      block:
        - name: extract the rhcos url from meta
          uri:
            url: "https://raw.githubusercontent.com/openshift/installer/master/data/data/rhcos.json"
          register: result
        - name: extract the openstack image
          set_fact:
            qcow_url_compressed: "{{ result.json.baseURI + result.json.images.openstack.path }}"
        - name: download file {{ qcow_path }}.gz
          command: "curl --compressed -J -L -o {{ qcow_path }}.gz  {{ qcow_url_compressed }}"
          register: download
        - name: uncompress file {{ qcow_path }}.gz
          command: "gunzip {{ qcow_path }}.gz"
      when: st.stat.exists == False
  tasks:
    - name: update template
      include_tasks: update-template.yaml
      loop: "{{ templates }}"